Traceback (most recent call last):
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/theo/research/12860_tutorial/envs/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## specify time for plotting
plot_time = "2022-9"

## blank canvas to plot on
fig = plt.figure()

## draw background map of Atlantic
fig, ax = plot_setup_atlantic(fig)

## plot the data
plot_data = ax.contourf(
    data.longitude,
    data.latitude,
    data.sel(time=plot_time).squeeze(),
    transform=ccrs.PlateCarree(),
    levels=10,
    extend="both",
    cmap="cmo.thermal",
)

## create colorbath
colorbar = fig.colorbar(plot_data, label=r"$K$")

## Mark Woods Hole on map
ax.scatter(
    288.5, 41.5, transform=ccrs.PlateCarree(), marker="*", c="k", s=50, zorder=10
)

## label
ax.set_title(f"SST ({plot_time})")

plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 12[0m
[1;32m      8[0m fig, ax [38;5;241m=[39m plot_setup_atlantic(fig)
[1;32m     10[0m [38;5;66;03m## plot the data[39;00m
[1;32m     11[0m plot_data [38;5;241m=[39m ax[38;5;241m.[39mcontourf(
[0;32m---> 12[0m     [43mdata[49m[38;5;241m.[39mlongitude,
[1;32m     13[0m     data[38;5;241m.[39mlatitude,
[1;32m     14[0m     data[38;5;241m.[39msel(time[38;5;241m=[39mplot_time)[38;5;241m.[39msqueeze(),
[1;32m     15[0m     transform[38;5;241m=[39mccrs[38;5;241m.[39mPlateCarree(),
[1;32m     16[0m     levels[38;5;241m=[39m[38;5;241m10[39m,
[1;32m     17[0m     extend[38;5;241m=[39m[38;5;124m"[39m[38;5;124mboth[39m[38;5;124m"[39m,
[1;32m     18[0m     cmap[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcmo.thermal[39m[38;5;124m"[39m,
[1;32m     19[0m )
[1;32m     21[0m [38;5;66;03m## create colorbath[39;00m
[1;32m     22[0m colorbar [38;5;241m=[39m fig[38;5;241m.[39mcolorbar(plot_data, label[38;5;241m=[39m[38;5;124mr[39m[38;5;124m"[39m[38;5;124m$K$[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'data' is not defined

